# Board Configuration for OPPO F3 (CPH1609)
# MediaTek MT6750 / MT6755 Platform
# Android 6.0.1 Marshmallow

# Platform
TARGET_BOARD_PLATFORM := mt6750
TARGET_BOOTLOADER_BOARD_NAME := mt6750
TARGET_BOARD_PLATFORM_GPU := Mali-T860 MP2

# CPU Architecture
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a53

# 64-bit support
TARGET_64_BIT := false
TARGET_SUPPORTS_32_BIT_APPS := true
TARGET_SUPPORTS_64_BIT_APPS := false

# Kernel
TARGET_PREBUILT_KERNEL := device/oppo/CPH1609/prebuilt/kernel
TARGET_KERNEL_ARCH := arm
TARGET_KERNEL_HEADER_ARCH := arm
BOARD_KERNEL_CMDLINE := console=ttyMT0,115200n1 androidboot.console=ttyMT0 androidboot.hardware=mt6750 androidboot.selinux=permissive
BOARD_KERNEL_BASE := 0x40000000
BOARD_KERNEL_PAGESIZE := 2048
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_RAMDISK_OFFSET := 0x04000000
BOARD_TAGS_OFFSET := 0xE000000
BOARD_MKBOOTIMG_ARGS := \
    --kernel_offset $(BOARD_KERNEL_OFFSET) \
    --ramdisk_offset $(BOARD_RAMDISK_OFFSET) \
    --tags_offset $(BOARD_TAGS_OFFSET) \
    --base $(BOARD_KERNEL_BASE) \
    --pagesize $(BOARD_KERNEL_PAGESIZE)

# Prebuilt Kernel
TARGET_PREBUILT_KERNEL := device/oppo/CPH1609/prebuilt/kernel
BOARD_MKBOOTIMG_ARGS += --kernel $(TARGET_PREBUILT_KERNEL)

# Partition Layout (MT6750 EMMC)
# Based on OPPO F3 CPH1609 scatter file analysis
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 16777216
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1887436800
BOARD_USERDATAIMAGE_PARTITION_SIZE := 27682406400
BOARD_CACHEIMAGE_PARTITION_SIZE := 268435456
BOARD_FLASH_BLOCK_SIZE := 131072

# File System
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_SPARSE_EXT4 := false
BOARD_CACHEIMAGE_FILE_SYSTEM_TYPE := ext4

# Recovery
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_SUPPRESS_SECURE_ERASE := true

# TWRP Specific
TW_THEME := portrait_hdpi
TW_MAX_BRIGHTNESS := 255
TW_DEFAULT_BRIGHTNESS := 128
TW_NO_SCREEN_TIMEOUT := true
TW_NO_BATT_PERCENT := false
TW_EXCLUDE_DEFAULT_CRYPTO := true
TW_INCLUDE_NTFS_3G := true
TW_USE_TOOLBOX := true
TW_INCLUDE_RESETPROP := true
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_FBE := false
TW_INPUT_BLACKLIST := "hbtp_vm"
TW_SCREEN_BLANK_ON_BOOT := true
TW_NO_USB_STORAGE := false

# MTK Specific
BOARD_USES_MTK_AUDIO := true
BOARD_USES_MTK_HARDWARE := true
BOARD_USESstąHARDWARE := false

# Display
TARGET_RUNNING_WITHOUT_SYNC_LAYER := true
TARGET_USES_64_BIT_BINDER := false

# SELinux
BOARD_KERNEL_SEPERATED_KERNEL := false
SELINUX_IGNORE_NEVERALLOWS := true

# Vendor
TARGET_COPY_OUT_VENDOR := vendor

# Encryption
TW_INCLUDE_CRYPTO := true
TW_CRYPTO_FS_TYPE := "ext4"
TW_CRYPTO_REAL_BLK_DEV := "/dev/block/platform/mtk-msdc.0/by-name/userdata"
TW_CRYPTO_MNT_POINT := "/data"
TW_CRYPTO_MNT_OPTIONS := "file Encryption"
